### ISSUE TITLE
thanks for the book

### ISSUE THREAD

**Issue by DanielZambelli** [sw-yx/codingcareer.com#14]
Hi @sw-yx, thanks for the book, but requesting a cancellation as per the "30 days, no questions asked" refund policy. Have sent and email even with feedback, but no answer yet. Receipt #1690-8677.

**Comment by swyxio** [comment]
hi Daniel! sorry about that - i straight up didnt even see the first email or the followup. it got caught in spam filter :( 

![image](https://user-images.githubusercontent.com/6764957/107820413-b51cbe00-6db5-11eb-8f10-2cf260b20c5d.png)


i am refunding and replying now. cheers.
